=== ludovicc/testng-debian/src/main/testng-1.0.dtd
<!-- ====================================================== -->
<!-- DTD for TestNG 1.0                                     -->
<!--                                                        -->
<!-- A suite is made of tests and parameters.               -->
<!--                                                        -->
<!-- A test is made of three parts:                         -->
<!-- * Parameters, which override the Suite parameters      -->
<!-- * Groups, made of two parts                            -->
<!-- * Classes, defining which classes are going to be part -->
<!--   of this test run                                     -->
<!--                                                        -->
<!-- In turn, groups are made of two parts:                 -->
<!-- * Definitions, which allow you to group groups into    -->
<!--   bigger groups                                        -->
<!-- * Runs, which defines the groups that the methods      -->
<!--   must belong to in order to be run during this test   -->
<!--                                                        -->
<!-- Full documentation:  http://testng.org                 -->
<!--                                                        -->
<!-- Cedric Beust & Alexandru Popescu                       -->
<!-- ====================================================== -->


<!-- A suite is the top-level element of a testng.xml file                  -->
<!ELEMENT suite (listeners|packages|test|parameter|method-selectors|suite-files)* >

<!-- Attributes: -->
<!--
  name:         The name of this suite (as it will appear in the reports)
  verbose:      (0-10) How verbose the output on the console will be.  
                This setting has no impact on the HTML reports.
                Default value: 1
  parallel:     (methods|tests) Whether TestNG should use different threads
                to run your tests (might speed up the process)
                Default value: none (no parallel mode)
  thread-count: An integer giving the size of the thread pool to use
                if you set parallel. Default value: 5
  annotations:  (javadoc|JDK5)  If "javadoc", TestNG will look for
                JavaDoc annotations in your sources, otherwise it will
                use JDK5 annotations. Default value: JDK5
  time-out:     the time to wait in milliseconds before aborting the
                method (if parallel="methods") or the test (parallel="tests")
-->
<!ATTLIST suite 
    name CDATA #REQUIRED
    verbose CDATA #IMPLIED
    parallel CDATA #IMPLIED
    thread-count CDATA #IMPLIED
    annotations CDATA #IMPLIED
    time-out CDATA #IMPLIED
>

<!-- A list of XML files that contain more suite descriptions -->
<!ELEMENT suite-files (suite-file)* >

<!ELEMENT suite-file ANY >
<!ATTLIST suite-file
    path CDATA #REQUIRED
>

<!-- Parameters can be defined at the <suite> or at the <test> level        -->
<!-- Parameters defined at the <test> level override parameters of the      -->
<!-- same name in <suite>.                                                  -->
<!-- Parameters are used to link Java method parameters to their actual     -->
<!-- value, defined here.                                                   -->
<!ELEMENT parameter ANY>
<!ATTLIST parameter
    name CDATA #REQUIRED
    value CDATA #REQUIRED >

<!-- Method selectors define user classes used to select which methods to   -->
<!-- run.  They need to implement org.testng.IMethodSelector                -->
<!ELEMENT method-selectors (method-selector*) >
<!ELEMENT method-selector ((selector-class)*|script) >
<!ELEMENT selector-class ANY>
<!ATTLIST selector-class
    name CDATA #REQUIRED
  priority CDATA #IMPLIED
>
<!ELEMENT script ANY>
<!ATTLIST script
    language CDATA #REQUIRED
>

<!-- A test contains parameters and classes.  Additionally, you can define  -->
<!-- additional groups ("groups of groups")                                 -->
<!ELEMENT test (method-selectors?,parameter*,groups?,packages?,classes?) >

<!-- Attributes:                                                            -->
<!--
  name:         The name of this test (as it will appear in the reports)
  junit:        (true|false) Whether to run in JUnit mode. Default value: false.
  verbose:      (0-10) How verbose the output on the console will be.
                This setting has no impact on the HTML reports.
                Default value: suite level verbose.
  parallel:     (methods) Whether TestNG should use different threads
                to run your tests (might speed up the process)
  thread-count: An integer giving teh size of the thread pool to be used if
                parallel mode is used. Overrides the suite level value.
  annotations:  (javadoc|JDK5)  If "javadoc", TestNG will look for
                JavaDoc annotations in your sources, otherwise it will
                use JDK5 annotations. Default value: JDK5
  time-out:     the time to wait in milliseconds before aborting
                the method (if parallel="methods") or the test (if parallel="tests")
  enabled:      flag to enable/disable current test. Default value: true 
-->
<!ATTLIST test
    name CDATA #REQUIRED 
    junit CDATA #IMPLIED
    verbose CDATA #IMPLIED
    parallel CDATA #IMPLIED
    thread-count CDATA #IMPLIED
    annotations CDATA #IMPLIED
    time-out CDATA #IMPLIED
    enabled CDATA #IMPLIED
>

<!-- Defines additional groups ("groups of groups") and also which groups   -->
<!-- to include in this test run                                            -->
<!ELEMENT groups (define*,run?) >

<!ELEMENT define (include*)>
<!ATTLIST define
    name CDATA #REQUIRED>

<!-- Defines which groups to include in the current group of groups         -->
<!ELEMENT include ANY>
<!ATTLIST include
    name CDATA #REQUIRED>

<!-- Defines which groups to exclude from the current group of groups       -->
<!ELEMENT exclude ANY>
<!ATTLIST exclude
    name CDATA #REQUIRED>

<!-- The subtag of groups used to define which groups should be run         -->
<!ELEMENT run (include?,exclude?)* >

<!-- The list of classes to include in this test                            -->
<!ELEMENT classes (class*) >
<!ELEMENT class (methods*) >
<!ATTLIST class
    name CDATA #REQUIRED >

<!-- The list of packages to include in this test                           -->
<!ELEMENT packages (package*) >
<!-- The package description. 
     If the package name ends with .* then subpackages are included too.
-->
<!ELEMENT package (include?,exclude?)*>
<!ATTLIST package
    name CDATA #REQUIRED >

<!-- The list of methods to include/exclude from this test                 -->
<!ELEMENT methods (include?,exclude?)* >

<!-- The list of listeners that will be passed to TestNG -->
<!ELEMENT listeners (listener*) >

<!ELEMENT listener ANY>
<!ATTLIST listener
    class-name CDATA #REQUIRED >

=== ludovicc/testng-debian/examples/testng.xml
<!DOCTYPE suite SYSTEM "http://beust.com/testng/testng-1.0.dtd" >
  
<suite name="Example" verbose="1">

  <listeners>
    <listener class-name="priority.PriorityInterceptor" />
  </listeners>
  
  <test name="Simple example" >
<!--
      <groups>
      <run>
        <include name="assert" />
        <include name="fail" />
        <include name="odd" />
        <include name="even" />
        <exclude name="broken" />
      </run>        
    </groups>
-->
    <classes>
      <class name="example1.Test1" />
    </classes>
  </test>
  
  <test name="Method interceptor example" >
    <classes>
      <class name="priority.PriorityTest" />
    </classes>
  </test>

</suite>

=== ludovicc/testng-debian/test-14/testng.xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="TestNG JDK 1.4" verbose="1" parallel="false" 
  thread-count="2" annotations="javadoc">

   <test name="Dependents">
    <parameter name="foo" value="Cedric" />
     <classes>
       <class name="test.dependent.OrderMethodTest" />
       <class name="test.dependent.DependentTest" />
       <class name="test.dependent.SampleDependentMethods" />
       <class name="test.dependent.SampleDependentMethods2" />
       <class name="test.dependent.SampleDependentMethods3" />
       <class name="test.dependent.SampleDependentConfigurationMethods"/>
       <class name="test.dependent.ClassDependsOnGroups"/>
       <class name="test.dependent.DependsWithRegexp"/>
       <class name="test.dependent.DependentAlwaysRunTest" />
       <class name="test.dependent.TestngTest" />
    </classes>
   </test>
	
  <test name="Nopackage">
   <groups>
	   <run>
			<include name="nopackage"/>
		</run>
	</groups>

    <classes>
	        <class name="NoPackageTest" />
    </classes>
  </test>

   <parameter name="first-name" value="Cedric"/>
<!-- -->
   <test name="Regression1" >
     <groups>
       <define name="evenodd">
         <include name="even" />
         <include name="odd" />
       </define>
       <run>
         <exclude name="excludeThisGroup" />
       </run>
     </groups>

     <classes>
       <class name="test.parameters.ParameterSample" />
       <class name="test.parameters.ParameterTest" />

       <class name="test.Test1" />
       <class name="test.Test2" />
       <class name="test.CtorCalledOnce" />
       <class name="test.expectedexceptions.ExpectedExceptionsTest" />
       <class name="test.access.PrivateAccessConfigurationMethods" />
     </classes>
   </test>
<!-- -->
<!-- -->
   <test name="Regression2">
     <classes>
       <class name="test.Test1" />
       <class name="test.MethodTest" />
       <class name="test.sample.AfterClassCalledAtEnd"/>
       <class name="test.configuration.ConfigurationTest"/>
       <class name="test.configuration.MethodCallOrderTest"/>
       <class name="test.configuration.ExternalConfigurationClass"/>
       <class name="test.privatemethod.PrivateMethodTest$PrivateMethodInnerTest"/>
       <class name="test.multiple.TestMultiple"/>
       <class name="test.CommandLineTest"/>
       <class name="test.Test4" />
       <class name="test.enabled.VerifyEnabledTest" />
       <class name="test.mannotation.MAnnotationSampleTest" />
       <class name="test.abstractbaseclass.DummyTest" />
       <class name="test.thread.ThreadPoolSizeTest" />
       <class name="test.thread.SequentialTest" />
       <class name="test.configuration.GroupLessTest" />
       <class name="test.reports.ReportTest" />
     </classes>
   </test>
<!-- 
    THIS CANNOT WORK: cannot set the sourcedirs
-->

<!--
    <test name="BeforeTestMethod Behavior Regression">
        <classes>
            <class name="test.failedconfs.FailedBeforeTestMethodConfigurationBehaviorTest" />
        </classes>
    </test>
-->
    
<!-- -->
   <test name="Basic" >
     <classes>
       <class name="test.sample.Basic2" />
       <class name="test.sample.Basic1" />
     </classes>
   </test>
<!-- -->
<!-- -->
   <test name="Exclusion">
     <groups>
       <run>
         <exclude name="excludeThisGroup" />
       </run>
     </groups>
     <classes>
       <class name="test.Test2" />
     </classes>
   </test>
<!-- -->
<!-- -->

   <test name="Inheritance">
     <classes>
       <class name="test.SampleInheritance" />
     </classes>
   </test>
<!-- -->
   <test name="JUnit">
     <classes>
       <class name="test.JUnitTest1" />
     </classes>
   </test>
<!--   -->
<!-- FIXME
     <test name="PHolser">
        <classes>
       <class name="test.pholser.Demo" />
        <class name="test.pholser.Saboteur" />
        </classes>
     </test>
-->

<!-- -->
   <test name="Skip">
     <classes>
       <class name="test.dependent.DependentTest" />
     </classes>
   </test>
<!-- -->
   <!-- Test scopes -->

   <parameter name="parameter" value="out"/>
<!-- -->
   <test name="Test outer scope">
     <groups>
       <run>
         <include name="outer-group" />
       </run>
     </groups>
     <classes>
       <class name="test.sample.Scope" />
     </classes>
   </test>

   <test name="Test inner scope">
     <parameter name="parameter" value="in" />
     <groups>
       <run>
         <include name="inner-group" />
       </run>
     </groups>
     <classes>
       <class name="test.sample.Scope" />
     </classes>
   </test>

   <test name="AfterClassCalledAtEnd">
     <classes>
       <class name="test.sample.AfterClassCalledAtEnd"/>
     </classes>
   </test>
<!-- -->
<!-- DONE -->
   <test name="Triangle">
      <classes>
         <class name="test.triangle.Child1"/>
         <class name="test.triangle.Child2"/>
      </classes>
   </test>

   <test name="CheckTrianglePost">
      <parameter name="expected-calls" value="2"/>
      <classes>
         <class name="test.triangle.CheckCount"/>
      </classes>
   </test>
<!-- -->

   <!-- Test that we can declare groups and dependents on classes -->
<!-- DONE -->
   <test name="Test class groups 1" >
     <classes>
       <class name="test.classgroup.Second" />
       <class name="test.classgroup.First" />
     </classes>
   </test>

     <test name="Test class groups 2" >
     <classes>
       <class name="test.classgroup.First" />
       <class name="test.classgroup.Second" />
     </classes>
   </test>
<!-- -->
   <parameter name="factory-param" value="FactoryParam"/>
<!-- DONE -->
  <test name="Factory">
    <classes>
      <class name="test.factory.FactoryTest" />
      <class name="test.factory.VerifyFactoryTest" />
      <class name="test.factory.FactoryInSeparateClass" />
      <class name="test.factory.IInstanceFactory" />
    </classes>
  </test>
<!-- -->
<!-- -->
  <test name="TimeOut">
    <classes>
      <class name="test.Test3" />
    </classes>
  </test>
<!-- -->
  <test name="InvocationCount">
    <classes>
      <class name="test.InvocationAndSuccessPercentageTest" />
    </classes>
  </test>

  <!-- Test parameters for constructors -->  
  <parameter name="string" value="Cedric" />
  <parameter name="int" value="42" />
  <parameter name="boolean" value="true" />
  <parameter name="byte" value="43" />
  <parameter name="char" value="c" />
  <parameter name="double" value="44.0" />
  <parameter name="float" value="45.0" />
  <parameter name="long" value="46" />
  <parameter name="short" value="47" />

  <test name="Parameters for constructors">
    <classes>
      <class name="test.ParameterConstructorTest" />
    </classes>
  </test>

  <test name="DataProvider">
    <classes>
       <class name="test.dataprovider.Sample1Test" />
       <class name="test.dataprovider.IterableTest" />
       <class name="test.dataprovider.MultipleDataProviderTest" />
       <class name="test.dataprovider.ChildUsingParentDataProviderTest" />
       <class name="test.dataprovider.ChildDataProvider" />
    </classes>
  </test>

  <test name="InheritGroups">
    <groups>
      <run>
        <include name="group1" />
      </run>
    </groups>
    <classes>
      <class name="test.configuration.ConfigurationInheritGroupsSampleTest" />
    </classes>
  </test>
  
  <test name="Inheritance">
    <classes>
      <class name="test.inheritance.ClassScopeTest" />
    </classes>
  </test>
 

</suite>

=== ludovicc/testng-debian/test/src/test/testng106/testng-106.xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="TESTNG-106" verbose="3">
    <test name="myTest1">
        <classes>
            <class name="test.testng106.FailingSuiteFixture" />
            <class name="test.testng106.Test1"/>
        </classes>
    </test>
    <test name="myTest2">
        <classes>
            <class name="test.testng106.Test1"/>
        </classes>
    </test>
    <test name="myTest3">
        <classes>
            <class name="test.testng106.Test2"/>
        </classes>
    </test>
    <test name="myTest-last">
        <classes>
            <class name="test.testng106.Test2"/>
        </classes>
    </test>
</suite>
